apiVersion: v1
kind: Service
metadata:
  name: sss-service
  namespace: sss-ns
  labels:
    app: sss-label
spec:
  clusterIP: None
  selector:
    app: sss-label
  ports:
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sss
  namespace: sss-ns
spec:
  serviceName: "sss-service"
  replicas: 2
  selector:
    matchLabels:
      app: sss-label
  template:
    metadata:
      labels:
        app: sss-label
    spec:
      containers:
        - name: sss-containers
          image: nginx
          ports:
            - containerPort: 80
