apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    app: my-label
  template:
    metadata:
      labels:
        app: my-label
    spec:
      containers:
        - name: container
          image: nginx:1.14.2
          ports:
            - containerPort: 80
